#ifndef STATIC_SK_RUNTIME_EFFECT_BUILDER_BUILDER_CHILD_INTERNAL_H
#define STATIC_SK_RUNTIME_EFFECT_BUILDER_BUILDER_CHILD_INTERNAL_H
#include <set>
#include <map>
#include "include/effects/SkRuntimeEffect.h"
int static_sk_runtime_effect_builder_builder_child_make(SkRuntimeEffectBuilder::BuilderChild value);
SkRuntimeEffectBuilder::BuilderChild static_sk_runtime_effect_builder_builder_child_get(int key);
void static_sk_runtime_effect_builder_builder_child_set(int key, SkRuntimeEffectBuilder::BuilderChild value);
#endif // STATIC_SK_RUNTIME_EFFECT_BUILDER_BUILDER_CHILD_INTERNAL_H
