//
// Created by dolphilia on 2024/04/03.
//

#ifndef RAIA_SKIA_STATIC_SK_IMAGE_READ_PIXELS_CALLBACK_H
#define RAIA_SKIA_STATIC_SK_IMAGE_READ_PIXELS_CALLBACK_H

#endif //RAIA_SKIA_STATIC_SK_IMAGE_READ_PIXELS_CALLBACK_H
