mv -f ./raia-core/raia_core ./build/aarch64-macos-none/
mv -f ./raia-app/raia_app.dylib ./build/aarch64-macos-none/
mv -f ./raia-draw/raia_draw.dylib ./build/aarch64-macos-none/
mv -f ./raia-file/raia_file.dylib ./build/aarch64-macos-none/
mv -f ./raia-sound/raia_sound.dylib ./build/aarch64-macos-none/
mv -f ./raia-sdk/raia_sdk.dylib ./build/aarch64-macos-none/
mv -f ./raia-duktape/raia_duktape.dylib ./build/aarch64-macos-none/
mv -f ./raia-lua/raia_lua.dylib ./build/aarch64-macos-none/
mv -f ./raia-mruby/raia_mruby.dylib ./build/aarch64-macos-none/
