//
// Created by dolphilia on 2023/08/08.
//

#ifndef RAIA_GUI_RAIA_GLES_H
#define RAIA_GUI_RAIA_GLES_H

// MARK: GL ES 2.0

void raia_gl_active_texture (unsigned int texture);
void raia_gl_attach_shader (unsigned int program, unsigned int shader);
void raia_gl_bind_attrib_location (unsigned int program, unsigned int index, const char *name);
void raia_gl_bind_buffer (unsigned int target, unsigned int buffer);
void raia_gl_bind_framebuffer (unsigned int target, unsigned int framebuffer);
void raia_gl_bind_renderbuffer (unsigned int target, unsigned int renderbuffer);
void raia_gl_bind_texture (unsigned int target, unsigned int texture);
void raia_gl_blend_color (float red, float green, float blue, float alpha);
void raia_gl_blend_equation (unsigned int mode);
void raia_gl_blend_equation_separate (unsigned int modeRGB, unsigned int modeAlpha);
void raia_gl_blend_func (unsigned int sfactor, unsigned int dfactor);
void raia_gl_blend_func_separate (unsigned int sfactorRGB, unsigned int dfactorRGB, unsigned int sfactorAlpha, unsigned int dfactorAlpha);
void raia_gl_buffer_data (unsigned int target, int size, const void *data, unsigned int usage);
void raia_gl_buffer_sub_data (unsigned int target, int offset, int size, const void *data);
unsigned int raia_gl_check_framebuffer_status (unsigned int target);
void raia_gl_clear (unsigned int mask);
void raia_gl_clear_color (float red, float green, float blue, float alpha);
void raia_gl_clear_depth_f (float d);
void raia_gl_clear_stencil (int s);
void raia_gl_color_mask (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha);
void raia_gl_compile_shader (unsigned int shader);
void raia_gl_compressed_tex_image_2d (unsigned int target, int level, unsigned int internalformat, int width, int height, int border, int imageSize, const void *data);
void raia_gl_compressed_tex_sub_image_2d (unsigned int target, int level, int xoffset, int yoffset, int width, int height, unsigned int format, int imageSize, const void *data);
void raia_gl_copy_tex_image_2d (unsigned int target, int level, unsigned int internalformat, int x, int y, int width, int height, int border);
void raia_gl_copy_tex_sub_image_2d (unsigned int target, int level, int xoffset, int yoffset, int x, int y, int width, int height);
unsigned int raia_gl_create_program (void);
unsigned int raia_gl_create_shader (unsigned int type);
void raia_gl_cull_face (unsigned int mode);
void raia_gl_delete_buffers (int n, const void *buffers);
void raia_gl_delete_framebuffers (int n, const void *framebuffers);
void raia_gl_delete_program (unsigned int program);
void raia_gl_delete_renderbuffers (int n, const void *renderbuffers);
void raia_gl_delete_shader (unsigned int shader);
void raia_gl_delete_textures (int n, const void *textures);
void raia_gl_depth_func (unsigned int func);
void raia_gl_depth_mask (unsigned char flag);
void raia_gl_depth_range_f (float n, float f);
void raia_gl_detach_shader (unsigned int program, unsigned int shader);
void raia_gl_disable (unsigned int cap);
void raia_gl_disable_vertex_attrib_array (unsigned int index);
void raia_gl_draw_arrays (unsigned int mode, int first, int count);
void raia_gl_draw_elements (unsigned int mode, int count, unsigned int type, const void *indices);
void raia_gl_enable (unsigned int cap);
void raia_gl_enable_vertex_attrib_array (unsigned int index);
void raia_gl_finish (void);
void raia_gl_flush (void);
void raia_gl_framebuffer_renderbuffer (unsigned int target, unsigned int attachment, unsigned int renderbuffertarget, unsigned int renderbuffer);
void raia_gl_framebuffer_texture_2d (unsigned int target, unsigned int attachment, unsigned int textarget, unsigned int texture, int level);
void raia_gl_front_face (unsigned int mode);
void raia_gl_gen_buffers (int n, void *buffers);
void raia_gl_generate_mipmap (unsigned int target);
void raia_gl_gen_framebuffers (int n, void *framebuffers);
void raia_gl_gen_renderbuffers (int n, void *renderbuffers);
void raia_gl_gen_textures (int n, void *textures);
void raia_gl_get_active_attrib (unsigned int program, unsigned int index, int bufSize, void *length, void *size, void *type, char *name);
void raia_gl_get_active_uniform (unsigned int program, unsigned int index, int bufSize, void *length, void *size, void *type, char *name);
void raia_gl_get_attached_shaders (unsigned int program, int maxCount, void *count, void *shaders);
int raia_gl_get_attrib_location (unsigned int program, const char *name);
void raia_gl_get_boolean_v (unsigned int pname, unsigned char *data);
void raia_gl_get_buffer_parameter_iv (unsigned int target, unsigned int pname, void *params);
unsigned int raia_gl_get_error (void);
void raia_gl_get_float_v (unsigned int pname, void *data);
void raia_gl_get_framebuffer_attachment_parameter_iv (unsigned int target, unsigned int attachment, unsigned int pname, void *params);
void raia_gl_get_integer_v (unsigned int pname, void *data);
void raia_gl_get_program_iv (unsigned int program, unsigned int pname, void *params);
void raia_gl_get_program_info_log (unsigned int program, int bufSize, void *length, char *infoLog);
void raia_gl_get_renderbuffer_parameter_iv (unsigned int target, unsigned int pname, void *params);
void raia_gl_get_shader_iv (unsigned int shader, unsigned int pname, void *params);
void raia_gl_get_shader_info_log (unsigned int shader, int bufSize, void *length, char *infoLog);
void raia_gl_get_shader_precision_format (unsigned int shadertype, unsigned int precisiontype, void *range, void *precision);
void raia_gl_get_shader_source (unsigned int shader, int bufSize, void *length, char *source);
const unsigned char  *raia_gl_get_string (unsigned int name);
void raia_gl_get_tex_parameter_fv (unsigned int target, unsigned int pname, void *params);
void raia_gl_get_tex_parameter_iv (unsigned int target, unsigned int pname, void *params);
void raia_gl_get_uniform_fv (unsigned int program, int location, void *params);
void raia_gl_get_uniform_iv (unsigned int program, int location, void *params);
int raia_gl_get_uniform_location (unsigned int program, const char *name);
void raia_gl_get_vertex_attrib_fv (unsigned int index, unsigned int pname, void *params);
void raia_gl_get_vertex_attrib_iv (unsigned int index, unsigned int pname, void *params);
void raia_gl_get_vertex_attrib_pointer_v (unsigned int index, unsigned int pname, void **pointer);
void raia_gl_hint (unsigned int target, unsigned int mode);
unsigned char raia_gl_is_buffer (unsigned int buffer);
unsigned char raia_gl_is_enabled (unsigned int cap);
unsigned char raia_gl_is_framebuffer (unsigned int framebuffer);
unsigned char raia_gl_is_program (unsigned int program);
unsigned char raia_gl_is_renderbuffer (unsigned int renderbuffer);
unsigned char raia_gl_is_shader (unsigned int shader);
unsigned char raia_gl_is_texture (unsigned int texture);
void raia_gl_line_width (float width);
void raia_gl_link_program (unsigned int program);
void raia_gl_pixel_store_i (unsigned int pname, int param);
void raia_gl_polygon_offset (float factor, float units);
void raia_gl_read_pixels (int x, int y, int width, int height, unsigned int format, unsigned int type, void *pixels);
void raia_gl_release_shader_compiler (void);
void raia_gl_renderbuffer_storage (unsigned int target, unsigned int internalformat, int width, int height);
void raia_gl_sample_coverage (float value, unsigned char invert);
void raia_gl_scissor (int x, int y, int width, int height);
void raia_gl_shader_binary (int count, const void *shaders, unsigned int binaryformat, const void *binary, int length);
void raia_gl_shader_source (unsigned int shader, int count, const char *const*string, const void *length);
void raia_gl_stencil_func (unsigned int func, int ref, unsigned int mask);
void raia_gl_stencil_func_separate (unsigned int face, unsigned int func, int ref, unsigned int mask);
void raia_gl_stencil_mask (unsigned int mask);
void raia_gl_stencil_mask_separate (unsigned int face, unsigned int mask);
void raia_gl_stencil_op (unsigned int fail, unsigned int zfail, unsigned int zpass);
void raia_gl_stencil_op_separate (unsigned int face, unsigned int sfail, unsigned int dpfail, unsigned int dppass);
void raia_gl_tex_image_2d (unsigned int target, int level, int internalformat, int width, int height, int border, unsigned int format, unsigned int type, const void *pixels);
void raia_gl_tex_parameter_f (unsigned int target, unsigned int pname, float param);
void raia_gl_tex_parameter_fv (unsigned int target, unsigned int pname, const void *params);
void raia_gl_tex_parameter_i (unsigned int target, unsigned int pname, int param);
void raia_gl_tex_parameter_iv (unsigned int target, unsigned int pname, const void *params);
void raia_gl_tex_sub_image_2d (unsigned int target, int level, int xoffset, int yoffset, int width, int height, unsigned int format, unsigned int type, const void *pixels);
void raia_gl_uniform_1f (int location, float v0);
void raia_gl_uniform_1fv (int location, int count, const void *value);
void raia_gl_uniform_1i (int location, int v0);
void raia_gl_uniform_1iv (int location, int count, const void *value);
void raia_gl_uniform_2f (int location, float v0, float v1);
void raia_gl_uniform_2fv (int location, int count, const void *value);
void raia_gl_uniform_2i (int location, int v0, int v1);
void raia_gl_uniform_2iv (int location, int count, const void *value);
void raia_gl_uniform_3f (int location, float v0, float v1, float v2);
void raia_gl_uniform_3fv (int location, int count, const void *value);
void raia_gl_uniform_3i (int location, int v0, int v1, int v2);
void raia_gl_uniform_3iv (int location, int count, const void *value);
void raia_gl_uniform_4f (int location, float v0, float v1, float v2, float v3);
void raia_gl_uniform_4fv (int location, int count, const void *value);
void raia_gl_uniform_4i (int location, int v0, int v1, int v2, int v3);
void raia_gl_uniform_4iv (int location, int count, const void *value);
void raia_gl_uniform_matrix_2fv (int location, int count, unsigned char transpose, const void *value);
void raia_gl_uniform_matrix_3fv (int location, int count, unsigned char transpose, const void *value);
void raia_gl_uniform_matrix_4fv (int location, int count, unsigned char transpose, const void *value);
void raia_gl_use_program (unsigned int program);
void raia_gl_validate_program (unsigned int program);
void raia_gl_vertex_attrib_1f (unsigned int index, float x);
void raia_gl_vertex_attrib_1fv (unsigned int index, const void *v);
void raia_gl_vertex_attrib_2f (unsigned int index, float x, float y);
void raia_gl_vertex_attrib_2fv (unsigned int index, const void *v);
void raia_gl_vertex_attrib_3f (unsigned int index, float x, float y, float z);
void raia_gl_vertex_attrib_3fv (unsigned int index, const void *v);
void raia_gl_vertex_attrib_4f (unsigned int index, float x, float y, float z, float w);
void raia_gl_vertex_attrib_4fv (unsigned int index, const void *v);
void raia_gl_vertex_attrib_pointer (unsigned int index, int size, unsigned int type, unsigned char normalized, int stride, const void *pointer);
void raia_gl_viewport (int x, int y, int width, int height);

// MARK: GL ES 3.0

void raia_gl_read_buffer (unsigned int src);
void raia_gl_draw_range_elements (unsigned int mode, unsigned int start, unsigned int end, int count, unsigned int type, const void *indices);
void raia_gl_tex_image_3d (unsigned int target, int level, int internalformat, int width, int height, int depth, int border, unsigned int format, unsigned int type, const void *pixels);
void raia_gl_tex_sub_image_3d (unsigned int target, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, unsigned int format, unsigned int type, const void *pixels);
void raia_gl_copy_tex_sub_image_3d (unsigned int target, int level, int xoffset, int yoffset, int zoffset, int x, int y, int width, int height);
void raia_gl_compressed_tex_image_3d (unsigned int target, int level, unsigned int internalformat, int width, int height, int depth, int border, int imageSize, const void *data);
void raia_gl_compressed_tex_sub_image_3d (unsigned int target, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, unsigned int format, int imageSize, const void *data);
void raia_gl_gen_queries (int n, void *ids);
void raia_gl_delete_queries (int n, const void *ids);
unsigned char raia_gl_is_query (unsigned int id);
void raia_gl_begin_query (unsigned int target, unsigned int id);
void raia_gl_end_query (unsigned int target);
void raia_gl_get_query_iv (unsigned int target, unsigned int pname, void *params);
void raia_gl_get_query_object_uiv (unsigned int id, unsigned int pname, void *params);
unsigned char raia_gl_unmap_buffer (unsigned int target);
void raia_gl_get_buffer_pointer_v (unsigned int target, unsigned int pname, void **params);
void raia_gl_draw_buffers (int n, const void *bufs);
void raia_gl_uniform_matrix_2x3fv (int location, int count, unsigned char transpose, const void *value);
void raia_gl_uniform_matrix_3x2fv (int location, int count, unsigned char transpose, const void *value);
void raia_gl_uniform_matrix_2x4fv (int location, int count, unsigned char transpose, const void *value);
void raia_gl_uniform_matrix_4x2fv (int location, int count, unsigned char transpose, const void *value);
void raia_gl_uniform_matrix_3x4fv (int location, int count, unsigned char transpose, const void *value);
void raia_gl_uniform_matrix_4x3fv (int location, int count, unsigned char transpose, const void *value);
void raia_gl_blit_framebuffer (int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, unsigned int mask, unsigned int filter);
void raia_gl_renderbuffer_storage_multisample (unsigned int target, int samples, unsigned int internalformat, int width, int height);
void raia_gl_framebuffer_texture_layer (unsigned int target, unsigned int attachment, unsigned int texture, int level, int layer);
void *raia_gl_map_buffer_range (unsigned int target, int offset, int length, unsigned int access);
void raia_gl_flush_mapped_buffer_range (unsigned int target, int offset, int length);
void raia_gl_bind_vertex_array (unsigned int array);
void raia_gl_delete_vertex_arrays (int n, const void *arrays);
void raia_gl_gen_vertex_arrays (int n, void *arrays);
unsigned char raia_gl_is_vertex_array (unsigned int array);
void raia_gl_get_integer_i_v (unsigned int target, unsigned int index, void *data);
void raia_gl_begin_transform_feedback (unsigned int primitiveMode);
void raia_gl_end_transform_feedback (void);
void raia_gl_bind_buffer_range (unsigned int target, unsigned int index, unsigned int buffer, int offset, int size);
void raia_gl_bind_buffer_base (unsigned int target, unsigned int index, unsigned int buffer);
void raia_gl_transform_feedback_varyings (unsigned int program, int count, const char *const*varyings, unsigned int bufferMode);
void raia_gl_get_transform_feedback_varying (unsigned int program, unsigned int index, int bufSize, void *length, void *size, void *type, char *name);
void raia_gl_vertex_attrib_i_pointer (unsigned int index, int size, unsigned int type, int stride, const void *pointer);
void raia_gl_get_vertex_attrib_iiv (unsigned int index, unsigned int pname, void *params);
void raia_gl_get_vertex_attrib_iuiv (unsigned int index, unsigned int pname, void *params);
void raia_gl_vertex_attrib_i4i (unsigned int index, int x, int y, int z, int w);
void raia_gl_vertex_attrib_i4ui (unsigned int index, unsigned int x, unsigned int y, unsigned int z, unsigned int w);
void raia_gl_vertex_attrib_i4iv (unsigned int index, const void *v);
void raia_gl_vertex_attrib_i4uiv (unsigned int index, const void *v);
void raia_gl_get_uniform_uiv (unsigned int program, int location, void *params);
int raia_gl_get_frag_data_location (unsigned int program, const char *name);
void raia_gl_uniform_1ui (int location, unsigned int v0);
void raia_gl_uniform_2ui (int location, unsigned int v0, unsigned int v1);
void raia_gl_uniform_3ui (int location, unsigned int v0, unsigned int v1, unsigned int v2);
void raia_gl_uniform_4ui (int location, unsigned int v0, unsigned int v1, unsigned int v2, unsigned int v3);
void raia_gl_uniform_1uiv (int location, int count, const void *value);
void raia_gl_uniform_2uiv (int location, int count, const void *value);
void raia_gl_uniform_3uiv (int location, int count, const void *value);
void raia_gl_uniform_4uiv (int location, int count, const void *value);
void raia_gl_clear_buffer_iv (unsigned int buffer, int drawbuffer, const void *value);
void raia_gl_clear_buffer_uiv (unsigned int buffer, int drawbuffer, const void *value);
void raia_gl_clear_buffer_fv (unsigned int buffer, int drawbuffer, const void *value);
void raia_gl_clear_buffer_fi (unsigned int buffer, int drawbuffer, float depth, int stencil);
const unsigned char  *raia_gl_get_string_i (unsigned int name, unsigned int index);
void raia_gl_copy_buffer_sub_data (unsigned int readTarget, unsigned int writeTarget, int readOffset, int writeOffset, int size);
void raia_gl_get_uniform_indices (unsigned int program, int uniformCount, const char *const*uniformNames, void *uniformIndices);
void raia_gl_get_active_uniforms_iv (unsigned int program, int uniformCount, const void *uniformIndices, unsigned int pname, void *params);
unsigned int raia_gl_get_uniform_block_index (unsigned int program, const char *uniformBlockName);
void raia_gl_get_active_uniform_block_iv (unsigned int program, unsigned int uniformBlockIndex, unsigned int pname, void *params);
void raia_gl_get_active_uniform_block_name (unsigned int program, unsigned int uniformBlockIndex, int bufSize, void *length, char *uniformBlockName);
void raia_gl_uniform_block_binding (unsigned int program, unsigned int uniformBlockIndex, unsigned int uniformBlockBinding);
void raia_gl_draw_arrays_instanced (unsigned int mode, int first, int count, int instancecount);
void raia_gl_draw_elements_instanced (unsigned int mode, int count, unsigned int type, const void *indices, int instancecount);
void * raia_gl_fence_sync (unsigned int condition, unsigned int flags);
unsigned char raia_gl_is_sync (void * sync);
void raia_gl_delete_sync (void * sync);
unsigned int raia_gl_client_wait_sync (void * sync, unsigned int flags, unsigned long long timeout);
void raia_gl_wait_sync (void * sync, unsigned int flags, unsigned long long timeout);
void raia_gl_get_integer_64v (unsigned int pname,void *data);
void raia_gl_get_sync_iv (void * sync, unsigned int pname, int bufSize, void *length, void *values);
void raia_gl_get_integer_64i_v (unsigned int target, unsigned int index, void *data);
void raia_gl_get_buffer_parameter_i64v (unsigned int target, unsigned int pname, void *params);
void raia_gl_gen_samplers (int count, void *samplers);
void raia_gl_delete_samplers (int count, const void *samplers);
unsigned char raia_gl_is_sampler (unsigned int sampler);
void raia_gl_bind_sampler (unsigned int unit, unsigned int sampler);
void raia_gl_sampler_parameter_i (unsigned int sampler, unsigned int pname, int param);
void raia_gl_sampler_parameter_iv (unsigned int sampler, unsigned int pname, const void *param);
void raia_gl_sampler_parameter_f (unsigned int sampler, unsigned int pname, float param);
void raia_gl_sampler_parameter_fv (unsigned int sampler, unsigned int pname, const void *param);
void raia_gl_get_sampler_parameter_iv (unsigned int sampler, unsigned int pname, void *params);
void raia_gl_get_sampler_parameter_fv (unsigned int sampler, unsigned int pname, void *params);
void raia_gl_vertex_attrib_divisor (unsigned int index, unsigned int divisor);
void raia_gl_bind_transform_feedback (unsigned int target, unsigned int id);
void raia_gl_delete_transform_feedbacks (int n, const void *ids);
void raia_gl_gen_transform_feedbacks (int n, void *ids);
unsigned char raia_gl_is_transform_feedback (unsigned int id);
void raia_gl_pause_transform_feedback (void);
void raia_gl_resume_transform_feedback (void);
void raia_gl_get_program_binary (unsigned int program, int bufSize, void *length, void *binaryFormat, void *binary);
void raia_gl_program_binary (unsigned int program, unsigned int binaryFormat, const void *binary, int length);
void raia_gl_program_parameter_i (unsigned int program, unsigned int pname, int value);
void raia_gl_invalidate_framebuffer (unsigned int target, int numAttachments, const void *attachments);
void raia_gl_invalidate_sub_framebuffer (unsigned int target, int numAttachments, const void *attachments, int x, int y, int width, int height);
void raia_gl_tex_storage_2d (unsigned int target, int levels, unsigned int internalformat, int width, int height);
void raia_gl_tex_storage_3d (unsigned int target, int levels, unsigned int internalformat, int width, int height, int depth);
void raia_gl_get_internal_format_iv (unsigned int target, unsigned int internalformat, unsigned int pname, int bufSize, void *params);

// MARK: GL ES 3.1

void raia_gl_dispatch_compute (unsigned int num_groups_x, unsigned int num_groups_y, unsigned int num_groups_z);
void raia_gl_dispatch_compute_indirect (int indirect);
void raia_gl_draw_arrays_indirect (unsigned int mode, const void *indirect);
void raia_gl_draw_elements_indirect (unsigned int mode, unsigned int type, const void *indirect);
void raia_gl_framebuffer_parameter_i (unsigned int target, unsigned int pname, int param);
void raia_gl_get_framebuffer_parameter_iv (unsigned int target, unsigned int pname, void *params);
void raia_gl_get_program_interface_iv (unsigned int program, unsigned int programInterface, unsigned int pname, void *params);
unsigned int raia_gl_get_program_resource_index (unsigned int program, unsigned int programInterface, const char *name);
void raia_gl_get_program_resource_name (unsigned int program, unsigned int programInterface, unsigned int index, int bufSize, void *length, char *name);
void raia_gl_get_program_resource_iv (unsigned int program, unsigned int programInterface, unsigned int index, int propCount, const void *props, int bufSize, void *length, void *params);
int raia_gl_get_program_resource_location (unsigned int program, unsigned int programInterface, const char *name);
void raia_gl_use_program_stages (unsigned int pipeline, unsigned int stages, unsigned int program);
void raia_gl_active_shader_program (unsigned int pipeline, unsigned int program);
unsigned int raia_gl_create_shader_program_v (unsigned int type, int count, const char *const*strings);
void raia_gl_bind_program_pipeline (unsigned int pipeline);
void raia_gl_delete_program_pipelines (int n, const void *pipelines);
void raia_gl_gen_program_pipelines (int n, void *pipelines);
unsigned char raia_gl_is_program_pipeline (unsigned int pipeline);
void raia_gl_get_program_pipeline_iv (unsigned int pipeline, unsigned int pname, void *params);
void raia_gl_program_uniform_1i (unsigned int program, int location, int v0);
void raia_gl_program_uniform_2i (unsigned int program, int location, int v0, int v1);
void raia_gl_program_uniform_3i (unsigned int program, int location, int v0, int v1, int v2);
void raia_gl_program_uniform_4i (unsigned int program, int location, int v0, int v1, int v2, int v3);
void raia_gl_program_uniform_1ui (unsigned int program, int location, unsigned int v0);
void raia_gl_program_uniform_2ui (unsigned int program, int location, unsigned int v0, unsigned int v1);
void raia_gl_program_uniform_3ui (unsigned int program, int location, unsigned int v0, unsigned int v1, unsigned int v2);
void raia_gl_program_uniform_4ui (unsigned int program, int location, unsigned int v0, unsigned int v1, unsigned int v2, unsigned int v3);
void raia_gl_program_uniform_1f (unsigned int program, int location, float v0);
void raia_gl_program_uniform_2f (unsigned int program, int location, float v0, float v1);
void raia_gl_program_uniform_3f (unsigned int program, int location, float v0, float v1, float v2);
void raia_gl_program_uniform_4f (unsigned int program, int location, float v0, float v1, float v2, float v3);
void raia_gl_program_uniform_1iv (unsigned int program, int location, int count, const void *value);
void raia_gl_program_uniform_2iv (unsigned int program, int location, int count, const void *value);
void raia_gl_program_uniform_3iv (unsigned int program, int location, int count, const void *value);
void raia_gl_program_uniform_4iv (unsigned int program, int location, int count, const void *value);
void raia_gl_program_uniform_1uiv (unsigned int program, int location, int count, const void *value);
void raia_gl_program_uniform_2uiv (unsigned int program, int location, int count, const void *value);
void raia_gl_program_uniform_3uiv (unsigned int program, int location, int count, const void *value);
void raia_gl_program_uniform_4uiv (unsigned int program, int location, int count, const void *value);
void raia_gl_program_uniform_1fv (unsigned int program, int location, int count, const void *value);
void raia_gl_program_uniform_2fv (unsigned int program, int location, int count, const void *value);
void raia_gl_program_uniform_3fv (unsigned int program, int location, int count, const void *value);
void raia_gl_program_uniform_4fv (unsigned int program, int location, int count, const void *value);
void raia_gl_program_uniform_matrix_2fv (unsigned int program, int location, int count, unsigned char transpose, const void *value);
void raia_gl_program_uniform_matrix_3fv (unsigned int program, int location, int count, unsigned char transpose, const void *value);
void raia_gl_program_uniform_matrix_4fv (unsigned int program, int location, int count, unsigned char transpose, const void *value);
void raia_gl_program_uniform_matrix_2x3fv (unsigned int program, int location, int count, unsigned char transpose, const void *value);
void raia_gl_program_uniform_matrix_3x2fv (unsigned int program, int location, int count, unsigned char transpose, const void *value);
void raia_gl_program_uniform_matrix_2x4fv (unsigned int program, int location, int count, unsigned char transpose, const void *value);
void raia_gl_program_uniform_matrix_4x2fv (unsigned int program, int location, int count, unsigned char transpose, const void *value);
void raia_gl_program_uniform_matrix_3x4fv (unsigned int program, int location, int count, unsigned char transpose, const void *value);
void raia_gl_program_uniform_matrix_4x3fv (unsigned int program, int location, int count, unsigned char transpose, const void *value);
void raia_gl_validate_program_pipeline (unsigned int pipeline);
void raia_gl_get_program_pipeline_info_log (unsigned int pipeline, int bufSize, void *length, char *infoLog);
void raia_gl_bind_image_texture (unsigned int unit, unsigned int texture, int level, unsigned char layered, int layer, unsigned int access, unsigned int format);
void raia_gl_get_boolean_i_v (unsigned int target, unsigned int index, unsigned char *data);
void raia_gl_memory_barrier (unsigned int barriers);
void raia_gl_memory_barrier_by_region (unsigned int barriers);
void raia_gl_tex_storage_2d_multisample (unsigned int target, int samples, unsigned int internalformat, int width, int height, unsigned char fixedsamplelocations);
void raia_gl_get_multisample_fv (unsigned int pname, unsigned int index, void *val);
void raia_gl_sample_mask_i (unsigned int maskNumber, unsigned int mask);
void raia_gl_get_tex_level_parameter_iv (unsigned int target, int level, unsigned int pname, void *params);
void raia_gl_get_tex_level_parameter_fv (unsigned int target, int level, unsigned int pname, void *params);
void raia_gl_bind_vertex_buffer (unsigned int bindingindex, unsigned int buffer, int offset, int stride);
void raia_gl_vertex_attrib_format (unsigned int attribindex, int size, unsigned int type, unsigned char normalized, unsigned int relativeoffset);
void raia_gl_vertex_attrib_i_format (unsigned int attribindex, int size, unsigned int type, unsigned int relativeoffset);
void raia_gl_vertex_attrib_binding (unsigned int attribindex, unsigned int bindingindex);
void raia_gl_vertex_binding_divisor (unsigned int bindingindex, unsigned int divisor);

// MARK: GL ES 3.2

void raia_gl_blend_barrier (void);
void raia_gl_copy_image_sub_data (unsigned int srcName, unsigned int srcTarget, int srcLevel, int srcX, int srcY, int srcZ, unsigned int dstName, unsigned int dstTarget, int dstLevel, int dstX, int dstY, int dstZ, int srcWidth, int srcHeight, int srcDepth);
void raia_gl_debug_message_control (unsigned int source, unsigned int type, unsigned int severity, int count, const void *ids, unsigned char enabled);
void raia_gl_debug_message_insert (unsigned int source, unsigned int type, unsigned int id, unsigned int severity, int length, const char *buf);
void raia_gl_debug_message_callback (void * callback, const void *userParam);
unsigned int raia_gl_get_debug_message_log (unsigned int count, int bufSize, void *sources, void *types, void *ids, void *severities, void *lengths, char *messageLog);
void raia_gl_push_debug_group (unsigned int source, unsigned int id, int length, const char *message);
void raia_gl_pop_debug_group (void);
void raia_gl_object_label (unsigned int identifier, unsigned int name, int length, const char *label);
void raia_gl_get_object_label (unsigned int identifier, unsigned int name, int bufSize, void *length, char *label);
void raia_gl_object_ptr_label (const void *ptr, int length, const char *label);
void raia_gl_get_object_ptr_label (const void *ptr, int bufSize, void *length, char *label);
void raia_gl_get_pointer_v (unsigned int pname, void **params);
void raia_gl_enable_i (unsigned int target, unsigned int index);
void raia_gl_disable_i (unsigned int target, unsigned int index);
void raia_gl_blend_equation_i (unsigned int buf, unsigned int mode);
void raia_gl_blend_equation_separate_i (unsigned int buf, unsigned int modeRGB, unsigned int modeAlpha);
void raia_gl_blend_func_i (unsigned int buf, unsigned int src, unsigned int dst);
void raia_gl_blend_func_separate_i (unsigned int buf, unsigned int srcRGB, unsigned int dstRGB, unsigned int srcAlpha, unsigned int dstAlpha);
void raia_gl_color_mask_i (unsigned int index, unsigned char r, unsigned char g, unsigned char b, unsigned char a);
unsigned char raia_gl_is_enabled_i (unsigned int target, unsigned int index);
void raia_gl_draw_elements_base_vertex (unsigned int mode, int count, unsigned int type, const void *indices, int basevertex);
void raia_gl_draw_range_elements_base_vertex (unsigned int mode, unsigned int start, unsigned int end, int count, unsigned int type, const void *indices, int basevertex);
void raia_gl_draw_elements_instanced_base_vertex (unsigned int mode, int count, unsigned int type, const void *indices, int instancecount, int basevertex);
void raia_gl_framebuffer_texture (unsigned int target, unsigned int attachment, unsigned int texture, int level);
void raia_gl_primitive_bounding_box (float minX, float minY, float minZ, float minW, float maxX, float maxY, float maxZ, float maxW);
unsigned int raia_gl_get_graphics_reset_status (void);
void raia_gl_read_n_pixels (int x, int y, int width, int height, unsigned int format, unsigned int type, int bufSize, void *data);
void raia_gl_get_n_uniform_fv (unsigned int program, int location, int bufSize, void *params);
void raia_gl_get_n_uniform_iv (unsigned int program, int location, int bufSize, void *params);
void raia_gl_get_n_uniform_uiv (unsigned int program, int location, int bufSize, void *params);
void raia_gl_min_sample_shading (float value);
void raia_gl_patch_parameter_i (unsigned int pname, int value);
void raia_gl_tex_parameter_iiv (unsigned int target, unsigned int pname, const void *params);
void raia_gl_tex_parameter_iuiv (unsigned int target, unsigned int pname, const void *params);
void raia_gl_get_tex_parameter_iiv (unsigned int target, unsigned int pname, void *params);
void raia_gl_get_tex_parameter_iuiv (unsigned int target, unsigned int pname, void *params);
void raia_gl_sampler_parameter_iiv (unsigned int sampler, unsigned int pname, const void *param);
void raia_gl_sampler_parameter_iuiv (unsigned int sampler, unsigned int pname, const void *param);
void raia_gl_get_sampler_parameter_iiv (unsigned int sampler, unsigned int pname, void *params);
void raia_gl_get_sampler_parameter_iuiv (unsigned int sampler, unsigned int pname, void *params);
void raia_gl_tex_buffer (unsigned int target, unsigned int internalformat, unsigned int buffer);
void raia_gl_tex_buffer_range (unsigned int target, unsigned int internalformat, unsigned int buffer, int offset, int size);
void raia_gl_tex_storage_3d_multisample (unsigned int target, int samples, unsigned int internalformat, int width, int height, int depth, unsigned char fixedsamplelocations);

#endif //RAIA_GUI_RAIA_GLES_H
