
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 104
#define YY_END_OF_BUFFER 105
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[292] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  105,  103,   97,   97,
        5,    5,    7,  103,  103,  103,  103,  103,    3,  103,
        6,  102,   92,   92,  104,   93,   93,   98,   94,   94,
       99,   10,   90,  104,  104,  104,   95,   95,  100,   59,
       14,   14,   63,   12,  104,  104,  104,  104,   11,   60,
       11,   11,   11,  104,  104,  104,   96,   96,  101,   85,
       57,   80,   78,   79,   86,   81,   69,   70,   73,   71,
       62,   72,   61,   74,   15,   15,   77,   76,   67,   64,
       68,   84,   87,   16,    8,   75,    9,   88,   16,   82,

       65,   91,   66,   89,  104,  104,  104,  104,  104,  104,
       13,   58,   13,   13,   13,  104,  104,  104,   97,    5,
        5,    5,    0,    0,    0,    2,    5,    0,    0,    0,
        6,    1,   92,   93,   94,   10,   10,    0,    0,    0,
       10,    0,    0,   95,    0,   14,   14,   12,   12,    0,
        0,    0,   12,    0,    0,    0,    0,   11,   11,   11,
       11,    0,    0,    0,   11,   11,   11,    0,    0,   96,
       29,    0,   37,   30,   38,   23,   35,   24,   32,   25,
       33,   45,    0,   36,    0,   15,    0,    0,   15,   26,
       28,   44,   27,    0,   16,   16,    0,    0,    0,   21,

       20,   22,   17,   18,   19,   39,   40,   31,    0,   16,
        0,    0,    0,    0,    0,   13,   13,   13,   13,    0,
        0,    0,   13,   13,   13,    0,    0,    5,    5,    0,
        0,    0,    5,    0,    0,    0,    0,    0,    0,    0,
       14,    0,    0,    0,    0,    0,    0,   41,   34,   46,
       15,   51,   51,   43,    0,    0,   42,   47,    0,    0,
        0,    0,    5,    0,    0,    0,    4,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   48,    0,
        0,    0,    0,    0,    0,    0,   50,    0,    0,    0,
        0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   22,   21,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   31,   31,   31,   31,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   33,   32,   32,
       34,   35,   36,   37,   38,   39,   31,   31,   31,   31,

       31,   31,   32,   32,   32,   32,   32,   32,   32,   40,
       32,   32,   32,   41,   32,   42,   32,   32,   32,   43,
       32,   32,   44,   45,   46,   47,    1,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,    1,    1,   49,   50,   50,   50,   50,   50,   50,

       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   51,   51,   51,   52,   51,   51,   51,
       51,   51,   51,   51,   51,   51,    1,   51,   51,   53,
       53,   53,   53,   53,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[54] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[296] =
    {   0,
        0,   50,   53,   55,   57,   63,   78,    0,  130,    0,
      183,    0,  236,    0,  289,    0,  781,  782,  782,  778,
      339,    0,  782,    0,  731,  730,  729,   58,  782,    0,
      782,  782,  782,  774,  782,  782,  773,  782,  782,  772,
      782,  375,  782,  725,  724,  723,  782,  768,  782,  782,
       50,   55,  782,  411,  721,  720,  719,  717,  461,  782,
        0,    0,   72,  717,  716,  715,  782,  760,  782,  735,
      782,   64,  782,  734,   78,  782,  782,  782,   75,   76,
      782,   73,  741,  732,  104,  120,  782,  782,  725,   66,
      724,  721,  782,  497,  782,  520,  782,  719,    0,  782,

      782,   70,  782,  782,   87,  692,  685,  117,  680,  678,
      559,  782,    0,    0,  607,  678,  677,  676,  782,  646,
        0,    0,  675,  671,  670,    0,    0,  665,  663,  140,
      782,    0,  782,  782,  782,    0,    0,  662,  659,  658,
        0,  656,  654,  782,  133,  156,  380,    0,    0,  653,
      646,  644,    0,  642,  635,  652,  632,    0,    0,    0,
      674,  625,  623,  598,    0,    0,  694,  597,  593,  782,
      782,  389,  782,  614,  782,  613,  782,  782,  782,  782,
      782,  782,  620,  782,  137,  416,  425,  502,  523,  782,
      782,  782,  782,  606,    0,    0,  583,  575,  574,  782,

      782,  782,  782,  782,  782,  782,  782,  591,  587,    0,
      517,  539,  510,  527,  507,    0,    0,    0,  697,  506,
      505,  504,    0,    0,  706,  503,  494,    0,    0,  488,
      486,  477,    0,  473,  472,  468,  370,  461,  419,  402,
      401,  400,  392,  391,  415,  382,  594,  782,  782,  782,
      437,  599,  606,  782,  366,  364,  782,  782,  382,  355,
      374,  339,    0,  337,  335,  330,  372,  327,  325,  314,
      613,  316,  155,  115,  118,  160,  127,  700,  782,  126,
      142,  125,  722,  123,  102,   83,  782,   81,   78,   77,
      782,  753,  755,   68,   62

    } ;

static const flex_int16_t yy_def[296] =
    {   0,
      291,    1,  292,  292,  293,  293,  293,    7,  293,    9,
      291,   11,  291,   13,  291,   15,  291,  291,  291,  291,
      291,   21,  291,  294,  291,  291,  291,  291,  291,  295,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
       59,   59,   59,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,   94,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  111,  111,  111,  291,  291,  291,  291,  291,
       21,   21,  291,  291,  291,  294,   21,  291,  291,  291,
      291,  295,  291,  291,  291,   42,   42,  291,  291,  291,
       42,  291,  291,  291,  291,  291,  291,   54,   54,  291,
      291,  291,   54,  291,  291,  291,  291,   59,   59,   59,
       59,  291,  291,  291,   59,   59,   59,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,   94,   94,  291,  291,  291,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,   94,
      291,  291,  291,  291,  291,  111,  111,  111,  111,  291,
      291,  291,  111,  111,  111,  291,  291,  120,  120,  291,
      291,  291,   21,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  120,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
        0,  291,  291,  291,  291

    } ;

static const flex_int16_t yy_nxt[836] =
    {   0,
       18,   19,   20,   18,   21,   21,   18,   21,   21,   21,
       21,   21,   21,   18,   21,   21,   21,   21,   21,   22,
       22,   22,   21,   18,   18,   21,   18,   21,   18,   21,
       21,   21,   21,   23,   18,   18,   24,   21,   18,   21,
       21,   21,   21,   18,   21,   18,   21,   18,   25,   25,
       26,   26,   27,   28,   33,   34,   33,   34,   36,   37,
       38,  130,  132,   29,   36,   37,   38,  145,  126,  146,
      146,  146,  145,   30,  147,  147,  147,  165,   31,   39,
       40,   41,  166,  172,  172,  172,  131,  174,  176,  180,
      178,  191,  192,  172,  172,  207,  218,  160,  181,  182,

      177,  179,  290,  175,  289,  267,  167,   42,   42,   42,
       42,  165,  165,  165,  208,   42,  209,   42,   42,   42,
       42,  185,   43,  186,  186,  186,   44,   44,   45,   45,
       46,   47,   48,   49,  210,   50,  187,  185,  212,  189,
      189,  189,  288,  237,  286,  285,  188,  284,  282,   51,
       52,   52,  241,  241,  241,   53,  251,  251,  251,   54,
       54,   54,   54,  281,  211,  263,  280,   54,  131,   54,
       54,   54,   54,  145,  279,  146,  146,  146,   55,   55,
       56,   56,   57,   35,   35,   35,   58,   59,   60,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,

       59,   59,   61,   61,   61,   59,   59,   59,   59,   59,
       59,   59,   62,   62,   62,   62,   59,   63,   59,   59,
       59,   59,   62,   62,   62,   62,   59,   59,   59,   59,
       35,   64,   64,   65,   65,   66,   35,   67,   68,   69,
       70,   71,   72,   73,   74,   75,   76,   77,   78,   79,
       80,   81,   82,   83,   84,   85,   86,   86,   87,   88,
       89,   90,   91,   92,   93,   94,   94,   94,   94,   95,
       96,   97,   98,   99,  100,   94,   94,   94,   94,  101,
      102,  103,  104,   35,  105,  106,  107,  108,  109,   35,
       35,   35,  110,  111,  112,  111,  111,  111,  111,  111,

      111,  111,  111,  111,  111,  111,  111,  111,  113,  113,
      113,  111,  111,  111,  111,  111,  111,  111,  114,  114,
      114,  114,  111,  115,  111,  111,  111,  111,  114,  114,
      114,  114,  111,  111,  111,  111,   35,  116,  116,  117,
      117,  118,  120,  121,  121,  120,  121,  121,  121,  121,
      121,  121,  120,  121,  121,  121,  121,  121,  122,  122,
      122,  121,  120,  195,  121,  277,  121,  120,  121,  121,
      121,  121,  148,  267,  136,  276,  121,  233,  121,  121,
      121,  121,  275,  121,  263,  121,  218,  123,  123,  124,
      124,  125,  136,  274,  137,  137,  137,  145,  131,  147,

      147,  147,  210,  273,  136,  136,  136,  136,  247,  247,
      247,  272,  136,  195,  136,  136,  136,  136,  247,  247,
      241,  241,  241,  138,  138,  139,  139,  140,  148,  160,
      149,  149,  149,  185,  270,  186,  186,  186,  153,  269,
      148,  148,  148,  148,  252,  252,  252,  148,  148,  141,
      148,  148,  148,  148,  252,  252,  251,  251,  251,  150,
      150,  151,  151,  152,  157,  158,  268,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      159,  159,  159,  158,  158,  158,  158,  158,  158,  158,
      160,  160,  160,  160,  158,  161,  158,  158,  158,  158,

      160,  160,  160,  160,  158,  158,  158,  158,  136,  162,
      162,  163,  163,  164,  195,  127,  196,  196,  196,  266,
      233,  253,  253,  253,  265,  200,  195,  195,  195,  195,
      201,  253,  253,  264,  195,  263,  195,  195,  195,  195,
      185,  262,  189,  189,  189,  197,  197,  198,  198,  199,
      218,  227,  226,  218,  202,  214,  261,  260,  259,  203,
      204,  205,  215,  216,  210,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  217,  217,
      217,  216,  216,  216,  216,  216,  216,  216,  218,  218,
      218,  218,  216,  219,  216,  216,  216,  216,  218,  218,

      218,  218,  216,  216,  216,  216,  258,  220,  220,  221,
      221,  222,  223,  271,  271,  271,  257,  224,  252,  252,
      252,  256,  255,  271,  271,  253,  253,  253,  252,  252,
      195,  254,  278,  278,  278,  253,  253,  250,  249,  248,
      246,  225,  278,  278,  160,  169,  223,  223,  223,  120,
      228,  228,  120,  228,  228,  228,  228,  228,  228,  120,
      228,  228,  228,  228,  228,  229,  229,  229,  228,  120,
      168,  228,  160,  228,  120,  228,  228,  228,  228,  165,
      156,  245,  244,  228,  166,  228,  228,  228,  228,  153,
      228,  243,  228,  242,  230,  230,  231,  231,  232,  165,

      148,  240,  223,  141,  166,  239,  238,  224,  167,  136,
      236,  223,  127,  165,  165,  165,  224,  235,  234,  283,
      283,  283,  233,  227,  226,  218,  214,  213,  167,  283,
      283,  225,  211,  165,  165,  165,  223,  223,  223,  210,
      225,  287,  287,  287,  206,  223,  223,  223,  194,  193,
      190,  287,  287,   32,   32,   35,   35,  184,  183,  173,
      171,  170,  169,  168,  160,  156,  155,  154,  153,  144,
      143,  142,  141,  135,  134,  133,  129,  128,  127,  119,
      291,   17,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291
    } ;

static const flex_int16_t yy_chk[836] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    3,    3,    4,    4,    5,    5,
        5,   28,  295,    2,    6,    6,    6,   51,  294,   51,
       51,   51,   52,    2,   52,   52,   52,   63,    2,    7,
        7,    7,   63,   72,   72,   72,   28,   75,   79,   82,
       80,   90,   90,   72,   72,  102,  290,  289,   82,   82,

       79,   80,  288,   75,  286,  285,   63,    7,    7,    7,
        7,   63,   63,   63,  102,    7,  105,    7,    7,    7,
        7,   85,    7,   85,   85,   85,    7,    7,    7,    7,
        7,    9,    9,    9,  105,    9,   85,   86,  108,   86,
       86,   86,  284,  130,  282,  281,   85,  280,  277,    9,
        9,    9,  145,  145,  145,    9,  185,  185,  185,    9,
        9,    9,    9,  276,  108,  275,  274,    9,  130,    9,
        9,    9,    9,  146,  273,  146,  146,  146,    9,    9,
        9,    9,    9,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,  272,   21,  270,   21,   21,   21,   21,
       21,   21,  269,  237,  268,  267,   21,  266,   21,   21,
       21,   21,  265,   21,  264,   21,  262,   21,   21,   21,
       21,   21,   42,  261,   42,   42,   42,  147,  237,  147,

      147,  147,  260,  259,   42,   42,   42,   42,  172,  172,
      172,  256,   42,  255,   42,   42,   42,   42,  172,  172,
      241,  241,  241,   42,   42,   42,   42,   42,   54,  246,
       54,   54,   54,  186,  245,  186,  186,  186,  244,  243,
       54,   54,   54,   54,  187,  187,  187,  242,   54,  240,
       54,   54,   54,   54,  187,  187,  251,  251,  251,   54,
       54,   54,   54,   54,   59,   59,  239,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,

       59,   59,   59,   59,   59,   59,   59,   59,  238,   59,
       59,   59,   59,   59,   94,  236,   94,   94,   94,  235,
      234,  188,  188,  188,  232,   96,   94,   94,   94,   94,
       96,  188,  188,  231,   94,  230,   94,   94,   94,   94,
      189,  227,  189,  189,  189,   94,   94,   94,   94,   94,
      226,  222,  221,  220,   96,  215,  214,  213,  212,   96,
       96,   96,  111,  111,  211,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,

      111,  111,  111,  111,  111,  111,  209,  111,  111,  111,
      111,  111,  115,  247,  247,  247,  208,  115,  252,  252,
      252,  199,  198,  247,  247,  253,  253,  253,  252,  252,
      197,  194,  271,  271,  271,  253,  253,  183,  176,  174,
      169,  115,  271,  271,  168,  164,  115,  115,  115,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      163,  120,  162,  120,  120,  120,  120,  120,  120,  161,
      157,  156,  155,  120,  161,  120,  120,  120,  120,  154,
      120,  152,  120,  151,  120,  120,  120,  120,  120,  167,

      150,  143,  219,  142,  167,  140,  139,  219,  161,  138,
      129,  225,  128,  161,  161,  161,  225,  125,  124,  278,
      278,  278,  123,  118,  117,  116,  110,  109,  167,  278,
      278,  219,  107,  167,  167,  167,  219,  219,  219,  106,
      225,  283,  283,  283,   98,  225,  225,  225,   92,   91,
       89,  283,  283,  292,  292,  293,  293,   84,   83,   74,
       70,   68,   66,   65,   64,   58,   57,   56,   55,   48,
       46,   45,   44,   40,   37,   34,   27,   26,   25,   20,
       17,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
/* flex lexer.l */
/* gcc lex.yy.c -ll -o lexer */
#line 7 "lexer.l"
#include "parser.tab.h"
#include <stdio.h>
#include <stdlib.h>
#line 730 "lex.yy.c"
/* コメント */
/* ラベル */
/* 空白 */
/* 位置 */
/* 記号 */
/* 2文字以上の記号 */
/* 演算子 */
/* エスケープ文字 */
/* アルファベット */
/* UTF8 */
/* 数値 */
/* 色 */
/* KAGメッセージ用の記号 */
/* |{HAT} */
/* 予約語 */
/* キー */
/* 文字列 */
/*
 * 排他的スタート状態の場合: %x
 * 包含的スタート状態の場合: %s
 */

/* 字句解析のルール */
#line 754 "lex.yy.c"

#define INITIAL 0
#define STATE_COMMENT 1
#define STATE_INDENT 2
#define STATE_LABEL 3
#define STATE_AT_TAG 4
#define STATE_AT_TAG_STRING 5
#define STATE_TAG 6
#define STATE_TAG_STRING 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 197 "lexer.l"

#line 983 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 292 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 782 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 198 "lexer.l"
{puts("> コメント");BEGIN(STATE_COMMENT);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 199 "lexer.l"
{puts("> コメント");BEGIN(STATE_COMMENT);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 200 "lexer.l"
{BEGIN(STATE_LABEL);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 201 "lexer.l"
{BEGIN(STATE_INDENT);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 202 "lexer.l"
{yylval.string_value = strdup(yytext);return MESSAGE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 204 "lexer.l"
{/* ^@ */BEGIN(STATE_AT_TAG);return AT_TOL;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 205 "lexer.l"
{/* [ */BEGIN(STATE_TAG);return SQUARE_L;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 206 "lexer.l"
{/* [ */return SQUARE_L;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 207 "lexer.l"
{/* ] */BEGIN(INITIAL);return SQUARE_R;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 209 "lexer.l"
{yylval.string_value = strdup(yytext);return LABEL_KEY;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 211 "lexer.l"
{yylval.string_value = strdup(yytext);return TAG_STRING;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 212 "lexer.l"
{yylval.string_value = strdup(yytext);return TAG_KEY;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 213 "lexer.l"
{yylval.string_value = strdup(yytext);return TAG_STRING;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 214 "lexer.l"
{yylval.string_value = strdup(yytext);return NUMBER;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 215 "lexer.l"
{yylval.string_value = strdup(yytext);return NUMBER;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 216 "lexer.l"
{yylval.string_value = strdup(yytext);return TAG_KEY;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 218 "lexer.l"
{/* \n */return ESC_LF;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 219 "lexer.l"
{/* \r */return ESC_CR;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 220 "lexer.l"
{/* \t */return ESC_TAB;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 221 "lexer.l"
{/* \' */return ESC_QUOTE_SINGLE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 222 "lexer.l"
{/* \" */return ESC_QUOTE_DOUBLE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 223 "lexer.l"
{/* \\ */return ESC_BACK_SLASH;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 225 "lexer.l"
{/* ** */  return MUL_MUL;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 226 "lexer.l"
{/* ++ */  return INCREMENT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 227 "lexer.l"
{/* -- */  return DECREMENT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 228 "lexer.l"
{/* <= */  return ANGLE_L_EQUAL;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 229 "lexer.l"
{/* >= */  return ANGLE_R_EQUAL;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 230 "lexer.l"
{/* == */  return EQUAL_EQUAL;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 231 "lexer.l"
{/* != */  return NOT_EQUAL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 232 "lexer.l"
{/* && */  return AND_AND;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 233 "lexer.l"
{/* || */  return OR_OR;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 234 "lexer.l"
{/* += */  return PLUS_EQUAL;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 235 "lexer.l"
{/* -= */  return MINUS_EQUAL;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 236 "lexer.l"
{/* **= */ return MUL_MUL_EQUAL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 237 "lexer.l"
{/* *= */  return MUL_EQUAL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 238 "lexer.l"
{/* /= */  return SLASH_EQUAL;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 239 "lexer.l"
{/* %= */  return PERCENT_EQUAL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 240 "lexer.l"
{/* &= */  return AND_EQUAL;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 241 "lexer.l"
{/* ^= */  return HAT_EQUAL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 242 "lexer.l"
{/* |= */  return OR_EQUAL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 243 "lexer.l"
{/* &&= */ return AND_AND_EQUAL;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 244 "lexer.l"
{/* ||= */ return OR_OR_EQUAL;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 245 "lexer.l"
{/* ??= */ return Q_Q_EQUAL;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 246 "lexer.l"
{/* => */  return ARROW;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 247 "lexer.l"
{/* -> */  return ARROW_SINGLE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 248 "lexer.l"
{/* ... */ return SPREAD;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 250 "lexer.l"
{return SPACE_UTF8_2BYTE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 251 "lexer.l"
{return SPACE_UTF8_3BYTE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 252 "lexer.l"
{return UTF8;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 254 "lexer.l"
{/* 0x[0-9a-fA-F]{6} */return HEX_COLOR;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 255 "lexer.l"
{/* 0x[0-9a-fA-F]+ */return NUMERAL_HEX;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 256 "lexer.l"
{/* [0-9]+.[0-9]+ */return FLOAT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 257 "lexer.l"
{/* [0-9][0-9]+ */yylval.string_value = strdup(yytext); return INTEGER;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 258 "lexer.l"
{/* 1-9 */yylval.string_value = strdup(yytext); return DIGIT_NON_ZERO;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 259 "lexer.l"
{/* 0 */yylval.string_value = strdup(yytext); return ZERO;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 261 "lexer.l"
{/* a-zA-A */yylval.string_value = strdup(yytext); return ALPHABET; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 263 "lexer.l"
{/* " */BEGIN(STATE_TAG_STRING);return QUOTE_DOUBLE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 264 "lexer.l"
{/* " */BEGIN(STATE_TAG);return QUOTE_DOUBLE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 265 "lexer.l"
{/* " */BEGIN(STATE_AT_TAG_STRING);return QUOTE_DOUBLE;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 266 "lexer.l"
{/* " */BEGIN(STATE_AT_TAG);return QUOTE_DOUBLE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 267 "lexer.l"
{/* . */return DOT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 268 "lexer.l"
{/* , */return COMMA;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 269 "lexer.l"
{/* = */return EQUAL;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 270 "lexer.l"
{/* = */return EQUAL;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 271 "lexer.l"
{/* { */return CURLY_L;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 272 "lexer.l"
{/* } */return CURLY_R;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 273 "lexer.l"
{/* < */return ANGLE_L;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 274 "lexer.l"
{/* > */return ANGLE_R;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 275 "lexer.l"
{/* ( */return ROUND_L;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 276 "lexer.l"
{/* ( */return ROUND_R;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 277 "lexer.l"
{/* + */return PLUS;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 278 "lexer.l"
{/* - */return MINUS;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 279 "lexer.l"
{/* * */return MUL;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 280 "lexer.l"
{/* / */return SLASH;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 281 "lexer.l"
{/* \ */return BACK_SLASH;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 282 "lexer.l"
{/* ; */return SEMICOLON;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 283 "lexer.l"
{/* : */return COLON;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 284 "lexer.l"
{/* $ */return DOLLAR;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 285 "lexer.l"
{/* % */return PERCENT;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 286 "lexer.l"
{/* # */return SHARP;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 287 "lexer.l"
{/* ' */return QUOTE_SINGLE;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 288 "lexer.l"
{/* ` */return QUOTE_BACK;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 289 "lexer.l"
{/* _ */return UNDERSCORE;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 290 "lexer.l"
{/* ? */return QUESTION;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 291 "lexer.l"
{/* ! */return NOT;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 292 "lexer.l"
{/* & */return AND;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 293 "lexer.l"
{/* @ */return AT;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 294 "lexer.l"
{/* ^ */return HAT;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 295 "lexer.l"
{/* ~ */return TILDE;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 296 "lexer.l"
{/* | */return OR;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 297 "lexer.l"
{/* | */return OR;}
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 299 "lexer.l"
{BEGIN(INITIAL);return EOL;}
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 300 "lexer.l"
{BEGIN(INITIAL);return EOL;}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 301 "lexer.l"
{BEGIN(INITIAL);return EOL;}
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 302 "lexer.l"
{BEGIN(INITIAL);return EOL;}
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 303 "lexer.l"
{return EOL;}
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 304 "lexer.l"
{return EOL;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 305 "lexer.l"
{}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 306 "lexer.l"
{}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 307 "lexer.l"
{}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 308 "lexer.l"
{}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 310 "lexer.l"
{}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 311 "lexer.l"
{}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 312 "lexer.l"
ECHO;
	YY_BREAK
#line 1567 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STATE_COMMENT):
case YY_STATE_EOF(STATE_INDENT):
case YY_STATE_EOF(STATE_LABEL):
case YY_STATE_EOF(STATE_AT_TAG):
case YY_STATE_EOF(STATE_AT_TAG_STRING):
case YY_STATE_EOF(STATE_TAG):
case YY_STATE_EOF(STATE_TAG_STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 292 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 292 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 291);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 312 "lexer.l"


/*
<STATE_TAG>{SQUARE_L}                   {return SQUARE_L;}
<STATE_TAG>{SQUARE_R}                   {return SQUARE_R;}
*/

/*{OPERATOR}          { printf("<OPERATOR>"); return(yytext[0]); }*/

void set_input_string(const char* in) {
  yy_scan_string(in);
}

void end_lexical_scan(void) {
  yy_delete_buffer(YY_CURRENT_BUFFER);
}

/* int main(void) {
    yylex();
    return 0;
} */

int yywrap() {
    return 1;
}

/* {NUMBER}          { printf("<NUMBER>");
                    yylval = atof(yytext);
                    return NUMBER; } */

/*

*/
