/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WindowCreator */

#ifndef _Included_WindowCreator
#define _Included_WindowCreator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WindowCreator
 * Method:    createWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WindowCreator_createWindow
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif