//
// Created by dolphilia on 2023/08/08.
//

#ifndef RAIA_GUI_RAIA_GLES_H
#define RAIA_GUI_RAIA_GLES_H

#include "GLES3/gl32.h"

// MARK: GL ES 2.0

void raia_gl_active_texture (GLenum texture);
void raia_gl_attach_shader (GLuint program, GLuint shader);
void raia_gl_bind_attrib_location (GLuint program, GLuint index, const GLchar *name);
void raia_gl_bind_buffer (GLenum target, GLuint buffer);
void raia_gl_bind_framebuffer (GLenum target, GLuint framebuffer);
void raia_gl_bind_renderbuffer (GLenum target, GLuint renderbuffer);
void raia_gl_bind_texture (GLenum target, GLuint texture);
void raia_gl_blend_color (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void raia_gl_blend_equation (GLenum mode);
void raia_gl_blend_equation_separate (GLenum modeRGB, GLenum modeAlpha);
void raia_gl_blend_func (GLenum sfactor, GLenum dfactor);
void raia_gl_blend_func_separate (GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
void raia_gl_buffer_data (GLenum target, GLsizeiptr size, const void *data, GLenum usage);
void raia_gl_buffer_sub_data (GLenum target, GLintptr offset, GLsizeiptr size, const void *data);
GLenum raia_gl_check_framebuffer_status (GLenum target);
void raia_gl_clear (GLbitfield mask);
void raia_gl_clear_color (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void raia_gl_clear_depth_f (GLfloat d);
void raia_gl_clear_stencil (GLint s);
void raia_gl_color_mask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
void raia_gl_compile_shader (GLuint shader);
void raia_gl_compressed_tex_image_2d (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data);
void raia_gl_compressed_tex_sub_image_2d (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
void raia_gl_copy_tex_image_2d (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
void raia_gl_copy_tex_sub_image_2d (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
GLuint raia_gl_create_program (void);
GLuint raia_gl_create_shader (GLenum type);
void raia_gl_cull_face (GLenum mode);
void raia_gl_delete_buffers (GLsizei n, const GLuint *buffers);
void raia_gl_delete_framebuffers (GLsizei n, const GLuint *framebuffers);
void raia_gl_delete_program (GLuint program);
void raia_gl_delete_renderbuffers (GLsizei n, const GLuint *renderbuffers);
void raia_gl_delete_shader (GLuint shader);
void raia_gl_delete_textures (GLsizei n, const GLuint *textures);
void raia_gl_depth_func (GLenum func);
void raia_gl_depth_mask (GLboolean flag);
void raia_gl_depth_range_f (GLfloat n, GLfloat f);
void raia_gl_detach_shader (GLuint program, GLuint shader);
void raia_gl_disable (GLenum cap);
void raia_gl_disable_vertex_attrib_array (GLuint index);
void raia_gl_draw_arrays (GLenum mode, GLint first, GLsizei count);
void raia_gl_draw_elements (GLenum mode, GLsizei count, GLenum type, const void *indices);
void raia_gl_enable (GLenum cap);
void raia_gl_enable_vertex_attrib_array (GLuint index);
void raia_gl_finish (void);
void raia_gl_flush (void);
void raia_gl_framebuffer_renderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
void raia_gl_framebuffer_texture_2d (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
void raia_gl_front_face (GLenum mode);
void raia_gl_gen_buffers (GLsizei n, GLuint *buffers);
void raia_gl_generate_mipmap (GLenum target);
void raia_gl_gen_framebuffers (GLsizei n, GLuint *framebuffers);
void raia_gl_gen_renderbuffers (GLsizei n, GLuint *renderbuffers);
void raia_gl_gen_textures (GLsizei n, GLuint *textures);
void raia_gl_get_active_attrib (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void raia_gl_get_active_uniform (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void raia_gl_get_attached_shaders (GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders);
GLint raia_gl_get_attrib_location (GLuint program, const GLchar *name);
void raia_gl_get_boolean_v (GLenum pname, GLboolean *data);
void raia_gl_get_buffer_parameter_iv (GLenum target, GLenum pname, GLint *params);
GLenum raia_gl_get_error (void);
void raia_gl_get_float_v (GLenum pname, GLfloat *data);
void raia_gl_get_framebuffer_attachment_parameter_iv (GLenum target, GLenum attachment, GLenum pname, GLint *params);
void raia_gl_get_integer_v (GLenum pname, GLint *data);
void raia_gl_get_program_iv (GLuint program, GLenum pname, GLint *params);
void raia_gl_get_program_info_log (GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void raia_gl_get_renderbuffer_parameter_iv (GLenum target, GLenum pname, GLint *params);
void raia_gl_get_shader_iv (GLuint shader, GLenum pname, GLint *params);
void raia_gl_get_shader_info_log (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void raia_gl_get_shader_precision_format (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision);
void raia_gl_get_shader_source (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source);
const GLubyte *raia_gl_get_string (GLenum name);
void raia_gl_get_tex_parameter_fv (GLenum target, GLenum pname, GLfloat *params);
void raia_gl_get_tex_parameter_iv (GLenum target, GLenum pname, GLint *params);
void raia_gl_get_uniform_fv (GLuint program, GLint location, GLfloat *params);
void raia_gl_get_uniform_iv (GLuint program, GLint location, GLint *params);
GLint raia_gl_get_uniform_location (GLuint program, const GLchar *name);
void raia_gl_get_vertex_attrib_fv (GLuint index, GLenum pname, GLfloat *params);
void raia_gl_get_vertex_attrib_iv (GLuint index, GLenum pname, GLint *params);
void raia_gl_get_vertex_attrib_pointer_v (GLuint index, GLenum pname, void **pointer);
void raia_gl_hint (GLenum target, GLenum mode);
GLboolean raia_gl_is_buffer (GLuint buffer);
GLboolean raia_gl_is_enabled (GLenum cap);
GLboolean raia_gl_is_framebuffer (GLuint framebuffer);
GLboolean raia_gl_is_program (GLuint program);
GLboolean raia_gl_is_renderbuffer (GLuint renderbuffer);
GLboolean raia_gl_is_shader (GLuint shader);
GLboolean raia_gl_is_texture (GLuint texture);
void raia_gl_line_width (GLfloat width);
void raia_gl_link_program (GLuint program);
void raia_gl_pixel_store_i (GLenum pname, GLint param);
void raia_gl_polygon_offset (GLfloat factor, GLfloat units);
void raia_gl_read_pixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
void raia_gl_release_shader_compiler (void);
void raia_gl_renderbuffer_storage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
void raia_gl_sample_coverage (GLfloat value, GLboolean invert);
void raia_gl_scissor (GLint x, GLint y, GLsizei width, GLsizei height);
void raia_gl_shader_binary (GLsizei count, const GLuint *shaders, GLenum binaryformat, const void *binary, GLsizei length);
void raia_gl_shader_source (GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length);
void raia_gl_stencil_func (GLenum func, GLint ref, GLuint mask);
void raia_gl_stencil_func_separate (GLenum face, GLenum func, GLint ref, GLuint mask);
void raia_gl_stencil_mask (GLuint mask);
void raia_gl_stencil_mask_separate (GLenum face, GLuint mask);
void raia_gl_stencil_op (GLenum fail, GLenum zfail, GLenum zpass);
void raia_gl_stencil_op_separate (GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
void raia_gl_tex_image_2d (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels);
void raia_gl_tex_parameter_f (GLenum target, GLenum pname, GLfloat param);
void raia_gl_tex_parameter_fv (GLenum target, GLenum pname, const GLfloat *params);
void raia_gl_tex_parameter_i (GLenum target, GLenum pname, GLint param);
void raia_gl_tex_parameter_iv (GLenum target, GLenum pname, const GLint *params);
void raia_gl_tex_sub_image_2d (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
void raia_gl_uniform_1f (GLint location, GLfloat v0);
void raia_gl_uniform_1fv (GLint location, GLsizei count, const GLfloat *value);
void raia_gl_uniform_1i (GLint location, GLint v0);
void raia_gl_uniform_1iv (GLint location, GLsizei count, const GLint *value);
void raia_gl_uniform_2f (GLint location, GLfloat v0, GLfloat v1);
void raia_gl_uniform_2fv (GLint location, GLsizei count, const GLfloat *value);
void raia_gl_uniform_2i (GLint location, GLint v0, GLint v1);
void raia_gl_uniform_2iv (GLint location, GLsizei count, const GLint *value);
void raia_gl_uniform_3f (GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void raia_gl_uniform_3fv (GLint location, GLsizei count, const GLfloat *value);
void raia_gl_uniform_3i (GLint location, GLint v0, GLint v1, GLint v2);
void raia_gl_uniform_3iv (GLint location, GLsizei count, const GLint *value);
void raia_gl_uniform_4f (GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void raia_gl_uniform_4fv (GLint location, GLsizei count, const GLfloat *value);
void raia_gl_uniform_4i (GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void raia_gl_uniform_4iv (GLint location, GLsizei count, const GLint *value);
void raia_gl_uniform_matrix_2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_uniform_matrix_3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_uniform_matrix_4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_use_program (GLuint program);
void raia_gl_validate_program (GLuint program);
void raia_gl_vertex_attrib_1f (GLuint index, GLfloat x);
void raia_gl_vertex_attrib_1fv (GLuint index, const GLfloat *v);
void raia_gl_vertex_attrib_2f (GLuint index, GLfloat x, GLfloat y);
void raia_gl_vertex_attrib_2fv (GLuint index, const GLfloat *v);
void raia_gl_vertex_attrib_3f (GLuint index, GLfloat x, GLfloat y, GLfloat z);
void raia_gl_vertex_attrib_3fv (GLuint index, const GLfloat *v);
void raia_gl_vertex_attrib_4f (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void raia_gl_vertex_attrib_4fv (GLuint index, const GLfloat *v);
void raia_gl_vertex_attrib_pointer (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer);
void raia_gl_viewport (GLint x, GLint y, GLsizei width, GLsizei height);

// MARK: GL ES 3.0

void raia_gl_read_buffer (GLenum src);
void raia_gl_draw_range_elements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices);
void raia_gl_tex_image_3d (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels);
void raia_gl_tex_sub_image_3d (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
void raia_gl_copy_tex_sub_image_3d (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void raia_gl_compressed_tex_image_3d (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data);
void raia_gl_compressed_tex_sub_image_3d (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data);
void raia_gl_gen_queries (GLsizei n, GLuint *ids);
void raia_gl_delete_queries (GLsizei n, const GLuint *ids);
GLboolean raia_gl_is_query (GLuint id);
void raia_gl_begin_query (GLenum target, GLuint id);
void raia_gl_end_query (GLenum target);
void raia_gl_get_query_iv (GLenum target, GLenum pname, GLint *params);
void raia_gl_get_query_object_uiv (GLuint id, GLenum pname, GLuint *params);
GLboolean raia_gl_unmap_buffer (GLenum target);
void raia_gl_get_buffer_pointer_v (GLenum target, GLenum pname, void **params);
void raia_gl_draw_buffers (GLsizei n, const GLenum *bufs);
void raia_gl_uniform_matrix_2x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_uniform_matrix_3x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_uniform_matrix_2x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_uniform_matrix_4x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_uniform_matrix_3x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_uniform_matrix_4x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_blit_framebuffer (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
void raia_gl_renderbuffer_storage_multisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
void raia_gl_framebuffer_texture_layer (GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
void *raia_gl_map_buffer_range (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
void raia_gl_flush_mapped_buffer_range (GLenum target, GLintptr offset, GLsizeiptr length);
void raia_gl_bind_vertex_array (GLuint array);
void raia_gl_delete_vertex_arrays (GLsizei n, const GLuint *arrays);
void raia_gl_gen_vertex_arrays (GLsizei n, GLuint *arrays);
GLboolean raia_gl_is_vertex_array (GLuint array);
void raia_gl_get_integer_i_v (GLenum target, GLuint index, GLint *data);
void raia_gl_begin_transform_feedback (GLenum primitiveMode);
void raia_gl_end_transform_feedback (void);
void raia_gl_bind_buffer_range (GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
void raia_gl_bind_buffer_base (GLenum target, GLuint index, GLuint buffer);
void raia_gl_transform_feedback_varyings (GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode);
void raia_gl_get_transform_feedback_varying (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name);
void raia_gl_vertex_attrib_i_pointer (GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer);
void raia_gl_get_vertex_attrib_iiv (GLuint index, GLenum pname, GLint *params);
void raia_gl_get_vertex_attrib_iuiv (GLuint index, GLenum pname, GLuint *params);
void raia_gl_vertex_attrib_i4i (GLuint index, GLint x, GLint y, GLint z, GLint w);
void raia_gl_vertex_attrib_i4ui (GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
void raia_gl_vertex_attrib_i4iv (GLuint index, const GLint *v);
void raia_gl_vertex_attrib_i4uiv (GLuint index, const GLuint *v);
void raia_gl_get_uniform_uiv (GLuint program, GLint location, GLuint *params);
GLint raia_gl_get_frag_data_location (GLuint program, const GLchar *name);
void raia_gl_uniform_1ui (GLint location, GLuint v0);
void raia_gl_uniform_2ui (GLint location, GLuint v0, GLuint v1);
void raia_gl_uniform_3ui (GLint location, GLuint v0, GLuint v1, GLuint v2);
void raia_gl_uniform_4ui (GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
void raia_gl_uniform_1uiv (GLint location, GLsizei count, const GLuint *value);
void raia_gl_uniform_2uiv (GLint location, GLsizei count, const GLuint *value);
void raia_gl_uniform_3uiv (GLint location, GLsizei count, const GLuint *value);
void raia_gl_uniform_4uiv (GLint location, GLsizei count, const GLuint *value);
void raia_gl_clear_buffer_iv (GLenum buffer, GLint drawbuffer, const GLint *value);
void raia_gl_clear_buffer_uiv (GLenum buffer, GLint drawbuffer, const GLuint *value);
void raia_gl_clear_buffer_fv (GLenum buffer, GLint drawbuffer, const GLfloat *value);
void raia_gl_clear_buffer_fi (GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
const GLubyte *raia_gl_get_string_i (GLenum name, GLuint index);
void raia_gl_copy_buffer_sub_data (GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
void raia_gl_get_uniform_indices (GLuint program, GLsizei uniformCount, const GLchar *const*uniformNames, GLuint *uniformIndices);
void raia_gl_get_active_uniforms_iv (GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params);
GLuint raia_gl_get_uniform_block_index (GLuint program, const GLchar *uniformBlockName);
void raia_gl_get_active_uniform_block_iv (GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params);
void raia_gl_get_active_uniform_block_name (GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName);
void raia_gl_uniform_block_binding (GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
void raia_gl_draw_arrays_instanced (GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
void raia_gl_draw_elements_instanced (GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount);
GLsync raia_gl_fence_sync (GLenum condition_, GLbitfield flags);
GLboolean raia_gl_is_sync (GLsync sync);
void raia_gl_delete_sync (GLsync sync);
GLenum raia_gl_client_wait_sync (GLsync sync, GLbitfield flags, GLuint64 timeout);
void raia_gl_wait_sync (GLsync sync, GLbitfield flags, GLuint64 timeout);
void raia_gl_get_integer_64v (GLenum pname, GLint64 *data);
void raia_gl_get_sync_iv (GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values);
void raia_gl_get_integer_64i_v (GLenum target, GLuint index, GLint64 *data);
void raia_gl_get_buffer_parameter_i64v (GLenum target, GLenum pname, GLint64 *params);
void raia_gl_gen_samplers (GLsizei count, GLuint *samplers);
void raia_gl_delete_samplers (GLsizei count, const GLuint *samplers);
GLboolean raia_gl_is_sampler (GLuint sampler);
void raia_gl_bind_sampler (GLuint unit, GLuint sampler);
void raia_gl_sampler_parameter_i (GLuint sampler, GLenum pname, GLint param);
void raia_gl_sampler_parameter_iv (GLuint sampler, GLenum pname, const GLint *param);
void raia_gl_sampler_parameter_f (GLuint sampler, GLenum pname, GLfloat param);
void raia_gl_sampler_parameter_fv (GLuint sampler, GLenum pname, const GLfloat *param);
void raia_gl_get_sampler_parameter_iv (GLuint sampler, GLenum pname, GLint *params);
void raia_gl_get_sampler_parameter_fv (GLuint sampler, GLenum pname, GLfloat *params);
void raia_gl_vertex_attrib_divisor (GLuint index, GLuint divisor);
void raia_gl_bind_transform_feedback (GLenum target, GLuint id);
void raia_gl_delete_transform_feedbacks (GLsizei n, const GLuint *ids);
void raia_gl_gen_transform_feedbacks (GLsizei n, GLuint *ids);
GLboolean raia_gl_is_transform_feedback (GLuint id);
void raia_gl_pause_transform_feedback (void);
void raia_gl_resume_transform_feedback (void);
void raia_gl_get_program_binary (GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary);
void raia_gl_program_binary (GLuint program, GLenum binaryFormat, const void *binary, GLsizei length);
void raia_gl_program_parameter_i (GLuint program, GLenum pname, GLint value);
void raia_gl_invalidate_framebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments);
void raia_gl_invalidate_sub_framebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height);
void raia_gl_tex_storage_2d (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
void raia_gl_tex_storage_3d (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
void raia_gl_get_internal_format_iv (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint *params);

// MARK: GL ES 3.1

void raia_gl_dispatch_compute (GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
void raia_gl_dispatch_compute_indirect (GLintptr indirect);
void raia_gl_draw_arrays_indirect (GLenum mode, const void *indirect);
void raia_gl_draw_elements_indirect (GLenum mode, GLenum type, const void *indirect);
void raia_gl_framebuffer_parameter_i (GLenum target, GLenum pname, GLint param);
void raia_gl_get_framebuffer_parameter_iv (GLenum target, GLenum pname, GLint *params);
void raia_gl_get_program_interface_iv (GLuint program, GLenum programInterface, GLenum pname, GLint *params);
GLuint raia_gl_get_program_resource_index (GLuint program, GLenum programInterface, const GLchar *name);
void raia_gl_get_program_resource_name (GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
void raia_gl_get_program_resource_iv (GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei bufSize, GLsizei *length, GLint *params);
GLint raia_gl_get_program_resource_location (GLuint program, GLenum programInterface, const GLchar *name);
void raia_gl_use_program_stages (GLuint pipeline, GLbitfield stages, GLuint program);
void raia_gl_active_shader_program (GLuint pipeline, GLuint program);
GLuint raia_gl_create_shader_program_v (GLenum type, GLsizei count, const GLchar *const*strings);
void raia_gl_bind_program_pipeline (GLuint pipeline);
void raia_gl_delete_program_pipelines (GLsizei n, const GLuint *pipelines);
void raia_gl_gen_program_pipelines (GLsizei n, GLuint *pipelines);
GLboolean raia_gl_is_program_pipeline (GLuint pipeline);
void raia_gl_get_program_pipeline_iv (GLuint pipeline, GLenum pname, GLint *params);
void raia_gl_program_uniform_1i (GLuint program, GLint location, GLint v0);
void raia_gl_program_uniform_2i (GLuint program, GLint location, GLint v0, GLint v1);
void raia_gl_program_uniform_3i (GLuint program, GLint location, GLint v0, GLint v1, GLint v2);
void raia_gl_program_uniform_4i (GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void raia_gl_program_uniform_1ui (GLuint program, GLint location, GLuint v0);
void raia_gl_program_uniform_2ui (GLuint program, GLint location, GLuint v0, GLuint v1);
void raia_gl_program_uniform_3ui (GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2);
void raia_gl_program_uniform_4ui (GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
void raia_gl_program_uniform_1f (GLuint program, GLint location, GLfloat v0);
void raia_gl_program_uniform_2f (GLuint program, GLint location, GLfloat v0, GLfloat v1);
void raia_gl_program_uniform_3f (GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void raia_gl_program_uniform_4f (GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void raia_gl_program_uniform_1iv (GLuint program, GLint location, GLsizei count, const GLint *value);
void raia_gl_program_uniform_2iv (GLuint program, GLint location, GLsizei count, const GLint *value);
void raia_gl_program_uniform_3iv (GLuint program, GLint location, GLsizei count, const GLint *value);
void raia_gl_program_uniform_4iv (GLuint program, GLint location, GLsizei count, const GLint *value);
void raia_gl_program_uniform_1uiv (GLuint program, GLint location, GLsizei count, const GLuint *value);
void raia_gl_program_uniform_2uiv (GLuint program, GLint location, GLsizei count, const GLuint *value);
void raia_gl_program_uniform_3uiv (GLuint program, GLint location, GLsizei count, const GLuint *value);
void raia_gl_program_uniform_4uiv (GLuint program, GLint location, GLsizei count, const GLuint *value);
void raia_gl_program_uniform_1fv (GLuint program, GLint location, GLsizei count, const GLfloat *value);
void raia_gl_program_uniform_2fv (GLuint program, GLint location, GLsizei count, const GLfloat *value);
void raia_gl_program_uniform_3fv (GLuint program, GLint location, GLsizei count, const GLfloat *value);
void raia_gl_program_uniform_4fv (GLuint program, GLint location, GLsizei count, const GLfloat *value);
void raia_gl_program_uniform_matrix_2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_program_uniform_matrix_3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_program_uniform_matrix_4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_program_uniform_matrix_2x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_program_uniform_matrix_3x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_program_uniform_matrix_2x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_program_uniform_matrix_4x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_program_uniform_matrix_3x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_program_uniform_matrix_4x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void raia_gl_validate_program_pipeline (GLuint pipeline);
void raia_gl_get_program_pipeline_info_log (GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void raia_gl_bind_image_texture (GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
void raia_gl_get_boolean_i_v (GLenum target, GLuint index, GLboolean *data);
void raia_gl_memory_barrier (GLbitfield barriers);
void raia_gl_memory_barrier_by_region (GLbitfield barriers);
void raia_gl_tex_storage_2d_multisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
void raia_gl_get_multisample_fv (GLenum pname, GLuint index, GLfloat *val);
void raia_gl_sample_mask_i (GLuint maskNumber, GLbitfield mask);
void raia_gl_get_tex_level_parameter_iv (GLenum target, GLint level, GLenum pname, GLint *params);
void raia_gl_get_tex_level_parameter_fv (GLenum target, GLint level, GLenum pname, GLfloat *params);
void raia_gl_bind_vertex_buffer (GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
void raia_gl_vertex_attrib_format (GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
void raia_gl_vertex_attrib_i_format (GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
void raia_gl_vertex_attrib_binding (GLuint attribindex, GLuint bindingindex);
void raia_gl_vertex_binding_divisor (GLuint bindingindex, GLuint divisor);

// MARK: GL ES 3.2

void raia_gl_blend_barrier (void);
void raia_gl_copy_image_sub_data (GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth);
void raia_gl_debug_message_control (GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled);
void raia_gl_debug_message_insert (GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf);
void raia_gl_debug_message_callback (GLDEBUGPROC callback, const void *userParam);
GLuint raia_gl_get_debug_message_log (GLuint count, GLsizei bufSize, GLenum *sources, GLenum *types, GLuint *ids, GLenum *severities, GLsizei *lengths, GLchar *messageLog);
void raia_gl_push_debug_group (GLenum source, GLuint id, GLsizei length, const GLchar *message);
void raia_gl_pop_debug_group (void);
void raia_gl_object_label (GLenum identifier, GLuint name, GLsizei length, const GLchar *label);
void raia_gl_get_object_label (GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label);
void raia_gl_object_ptr_label (const void *ptr, GLsizei length, const GLchar *label);
void raia_gl_get_object_ptr_label (const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label);
void raia_gl_get_pointer_v (GLenum pname, void **params);
void raia_gl_enable_i (GLenum target, GLuint index);
void raia_gl_disable_i (GLenum target, GLuint index);
void raia_gl_blend_equation_i (GLuint buf, GLenum mode);
void raia_gl_blend_equation_separate_i (GLuint buf, GLenum modeRGB, GLenum modeAlpha);
void raia_gl_blend_func_i (GLuint buf, GLenum src, GLenum dst);
void raia_gl_blend_func_separate_i (GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
void raia_gl_color_mask_i (GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a);
GLboolean raia_gl_is_enabled_i (GLenum target, GLuint index);
void raia_gl_draw_elements_base_vertex (GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex);
void raia_gl_draw_range_elements_base_vertex (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices, GLint basevertex);
void raia_gl_draw_elements_instanced_base_vertex (GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex);
void raia_gl_framebuffer_texture (GLenum target, GLenum attachment, GLuint texture, GLint level);
void raia_gl_primitive_bounding_box (GLfloat minX, GLfloat minY, GLfloat minZ, GLfloat minW, GLfloat maxX, GLfloat maxY, GLfloat maxZ, GLfloat maxW);
GLenum raia_gl_get_graphics_reset_status (void);
void raia_gl_read_n_pixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data);
void raia_gl_get_n_uniform_fv (GLuint program, GLint location, GLsizei bufSize, GLfloat *params);
void raia_gl_get_n_uniform_iv (GLuint program, GLint location, GLsizei bufSize, GLint *params);
void raia_gl_get_n_uniform_uiv (GLuint program, GLint location, GLsizei bufSize, GLuint *params);
void raia_gl_min_sample_shading (GLfloat value);
void raia_gl_patch_parameter_i (GLenum pname, GLint value);
void raia_gl_tex_parameter_iiv (GLenum target, GLenum pname, const GLint *params);
void raia_gl_tex_parameter_iuiv (GLenum target, GLenum pname, const GLuint *params);
void raia_gl_get_tex_parameter_iiv (GLenum target, GLenum pname, GLint *params);
void raia_gl_get_tex_parameter_iuiv (GLenum target, GLenum pname, GLuint *params);
void raia_gl_sampler_parameter_iiv (GLuint sampler, GLenum pname, const GLint *param);
void raia_gl_sampler_parameter_iuiv (GLuint sampler, GLenum pname, const GLuint *param);
void raia_gl_get_sampler_parameter_iiv (GLuint sampler, GLenum pname, GLint *params);
void raia_gl_get_sampler_parameter_iuiv (GLuint sampler, GLenum pname, GLuint *params);
void raia_gl_tex_buffer (GLenum target, GLenum internalformat, GLuint buffer);
void raia_gl_tex_buffer_range (GLenum target, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size);
void raia_gl_tex_storage_3d_multisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);

#endif //RAIA_GUI_RAIA_GLES_H
