set(IS_WINDOWS FALSE)
set(IS_MACOS FALSE)
set(IS_LINUX FALSE)
set(IS_X86_64 FALSE)
set(IS_X86 FALSE)
set(IS_ARM64 FALSE)
set(IS_ARM FALSE)
set(IS_DEBUG FALSE)
set(IS_RELEASE FALSE)

if(WIN32)
    set(IS_WINDOWS TRUE)
elseif(APPLE)
    set(IS_MACOS TRUE)
elseif(UNIX AND NOT APPLE)
    set(IS_LINUX TRUE)
endif()

if(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64" OR CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "AMD64")
    set(IS_X86_64 TRUE)
elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "i386")
    set(IS_X86 TRUE)
elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "arm64" OR CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "aarch64")
    set(IS_ARM64 TRUE)
elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "arm" OR CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "armv[0-9]+")
    set(IS_ARM TRUE)
endif()

if(CMAKE_BUILD_TYPE MATCHES Debug)
    set(IS_DEBUG TRUE)
elseif(CMAKE_BUILD_TYPE MATCHES Release)
    set(IS_RELEASE TRUE)
endif()

if(IS_DEBUG)
    if(IS_WINDOWS)
    elseif(IS_MACOS)
        if(IS_ARM64)
            set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/../../../../build/macos/arm64/debug)
            set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/../../../../build/macos/arm64/debug)
        elseif(IS_X86_64)
            set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/../../../../build/macos/x86_64/debug)
            set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/../../../../build/macos/x86_64/debug)
        endif()
    elseif(IS_LINUX)
    endif()
elseif(IS_RELEASE)
    if(IS_WINDOWS)
    elseif(IS_MACOS)
        if(IS_ARM64)
            set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/../../../../build/macos/arm64/release)
            set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/../../../../build/macos/arm64/release)
        elseif(IS_X86_64)
            set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/../../../../build/macos/x86_64/release)
            set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/../../../../build/macos/x86_64/release)
        endif()
    elseif(IS_LINUX)
    endif()
endif()


if(IS_WINDOWS)
elseif(IS_MACOS)
    if(IS_ARM64)
        include_directories(${PROJECT_SOURCE_DIR}/../../../../sdk/macos/arm64/include)
        link_directories(${PROJECT_SOURCE_DIR}/../../../../sdk/macos/arm64/lib)
    elseif(IS_X86_64)
        include_directories(${PROJECT_SOURCE_DIR}/../../../../sdk/macos/x86_64/include)
        link_directories(${PROJECT_SOURCE_DIR}/../../../../sdk/macos/x86_64/lib)
    endif()
elseif(IS_LINUX)
endif()