name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies on Ubuntu
        if: startsWith(runner.os, 'Linux')
        run: sudo apt-get install -y cmake zip xserver-xorg libxxf86vm-dev lxrandr x11-xserver-utils libxinerama-dev libxcursor-dev libxi-dev

      - name: Install dependencies on Windows
        if: startsWith(runner.os, 'Windows')
        run: choco install cmake zip

      - name: Create Build directory
        run: mkdir build

      - name: CMake Configure
        run: cmake -S . -B build

      - name: CMake Build
        run: cmake --build build --config Release